baseURL: 'https://walkergriggs.com'
locale: 'en-us'
title: 'Walker Griggs'
disableKinds: ["taxonomy"]
ignoreErrors: ["error-disable-taxonomy"]
pluralizeListTitles: false

markup:
        goldmark:
                renderer:
                        unsafe: true
        highlight:
                noClasses: false
                codeFences: true
                guessSyntax: false
                lineNos: false
                tabWidth: 4

params:
        author:
                email: "hello@walkergriggs.com"

permalinks:
        posts: "/:year/:month/:day/:contentbasename"
        pages: "/:slug"

menu:
        main:
                - name: Home.
                  url: ""
                  weight: 1
                - name: Writing.
                  url: "posts/"
                  weight: 2
                - name: Feed.
                  url: "/index.xml"
                  weight: 3
